version: '3'
services: 
  nginx:
    image: "noriom42/first-multi-nginx"
    ports:
      - '80:80'
    hostname: nginx
    mem_limit: 128m

  server:
    hostname: api
    image: "noriom42/first-multi-server"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
    mem_limit: 128m
  
  client:
    hostname: client
    image: "noriom42/first-multi-client"
    mem_limit: 128m
  
  worker:
    hostname: worker
    image: "noriom42/first-multi-worker"
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT